### ISSUE TITLE
Excessive memory usage using npx nest start service

### ISSUE THREAD

**Issue by av8ta** [juicycleff/ultimate-backend#60]
Firstly, wow this project looks super interesting! 

I ran into a snag spinning up each service as suggested in the docs:

```bash
NODE_ENV=staging npx nest start service-auth
```

Each service consumed about 2GB of memory on my poor little machine. With more than half a dozen services to spin up and my machine only having 8GB memory....  :scream: 

It appears to be related to this issue https://github.com/nestjs/nest/issues/2135 where it's established that ts-node is the culprit. tsc-watch is suggested as a solution there. Perhaps that would be a good idea? 

I got around the issue by building each service and running them with node from the dist directory however that felt awkward. Digging deeper I realised you're using docker (have used a little), terraform, and kubernetes (have not used either of them). I noticed development configs there alongside staging and production.... so perhaps I've misunderstood and there's a simpler way to manage devops in development?

**Comment by juicycleff** [comment]
@av8ta that's very true, I started to notice this issue on dev, and it's been low hanging due to the fact that I have a powerful computer. I will resolve it or if you can just send a PR. 

As for Terraform and Kubernetes, or even docker, theses are optional and mostly make life easier for running the services without worrying about setting up networking and all that. Terraform just helps you spin up a Kubernetes cluster with a few commands. I am assigning 1hr per day to write the documentation and helpfully explain what each piece does. Thanks for the interest, I believe it's high time NodeJS gets clearly designed boilerplates or template for building enterprise systems. 

Well when it comes to config, you can switch it up how you like. I personally prefer using Yaml for storing static configuration and having production and staging config there helps junior and intermediate developers get up and running. You can get your production config in a CI I use Azure pipeline and I do the same. I'm still making things beautiful and performant in the system. Also, a more resilient Event store catch up  patterns I have in pipeline

**Comment by juicycleff** [comment]
I could have a script that acts like the nest cli start command that speeds thing's up. I think I will make it a priority

**Comment by av8ta** [comment]
Thanks for the speedy reply. I agree totally with "I believe it's high time NodeJS gets clearly designed boilerplates or template for building enterprise systems." and I'm seriously considering using this in production. For now I'm just trying to work out how all the pieces fit together and perhaps as I gain understanding I can help with the documentation. 
I tried ```TS_NODE_TRANSPILE_ONLY=true npx nest start service-user --watch``` but it used only slightly less memory! I'll have a play with it tomorrow (it's midnight here) thanks for your time :)

**Comment by juicycleff** [comment]
@av8ta sure thing, I will look into fixing it the ts-node issue. Thank you :)

**Comment by mso1985** [comment]
Hi, awesome project! 
I have a question.. wich is the current way to start testing ?, i've followed README but gateway-admin wont connect to mongodb.

**Comment by juicycleff** [comment]
@mso1985 you should see the config folder, select the yaml file and you will see the mongo section at the top of the file. If your testing locally, just change the settings on development sub folder of the config folder.

**Comment by juicycleff** [comment]
You can switch from using webpack for compilation and should improve memory, you do that in the nest-cli.json file and setting `webpack` false.

```json
{
  "collection": "@nestjs/schematics",
  "sourceRoot": "apps/api-admin/src",
  "monorepo": true,
  "root": "apps/api-admin",
  "compilerOptions": {
    "webpack": true,
    "tsConfigPath": "apps/api-admin/tsconfig.app.json",
    "watchAssets": true
  },
  "projects": {

  }
}

```

**Comment by iamonuwa** [comment]
Best bet is to use the docker commands. Disabling the webpack will throw wrong path error for the .proto files.
